/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BiomassRouteImport } from './routes/biomass'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoadshieldRouteImport } from './routes/loadshield'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as WasteToEnergyRouteImport } from './routes/waste-to-energy'
import { Route as WindRouteImport } from './routes/wind'
import { Route as ZonesRouteImport } from './routes/zones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BiomassRoute = BiomassRouteImport.update({
  id: '/biomass',
  path: '/biomass',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadshieldRoute = LoadshieldRouteImport.update({
  id: '/loadshield',
  path: '/loadshield',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const WasteToEnergyRoute = WasteToEnergyRouteImport.update({
  id: '/waste-to-energy',
  path: '/waste-to-energy',
  getParentRoute: () => rootRouteImport,
} as any)
const WindRoute = WindRouteImport.update({
  id: '/wind',
  path: '/wind',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/biomass': typeof BiomassRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/loadshield': typeof LoadshieldRoute
  '/resources': typeof ResourcesRoute
  '/solar': typeof SolarRoute
  '/technology': typeof TechnologyRoute
  '/waste-to-energy': typeof WasteToEnergyRoute
  '/wind': typeof WindRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/biomass': typeof BiomassRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/loadshield': typeof LoadshieldRoute
  '/resources': typeof ResourcesRoute
  '/solar': typeof SolarRoute
  '/technology': typeof TechnologyRoute
  '/waste-to-energy': typeof WasteToEnergyRoute
  '/wind': typeof WindRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/biomass': typeof BiomassRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/loadshield': typeof LoadshieldRoute
  '/resources': typeof ResourcesRoute
  '/solar': typeof SolarRoute
  '/technology': typeof TechnologyRoute
  '/waste-to-energy': typeof WasteToEnergyRoute
  '/wind': typeof WindRoute
  '/zones': typeof ZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/biomass'
    | '/dashboard'
    | '/history'
    | '/loadshield'
    | '/resources'
    | '/solar'
    | '/technology'
    | '/waste-to-energy'
    | '/wind'
    | '/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/biomass'
    | '/dashboard'
    | '/history'
    | '/loadshield'
    | '/resources'
    | '/solar'
    | '/technology'
    | '/waste-to-energy'
    | '/wind'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/biomass'
    | '/dashboard'
    | '/history'
    | '/loadshield'
    | '/resources'
    | '/solar'
    | '/technology'
    | '/waste-to-energy'
    | '/wind'
    | '/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BiomassRoute: typeof BiomassRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoadshieldRoute: typeof LoadshieldRoute
  ResourcesRoute: typeof ResourcesRoute
  SolarRoute: typeof SolarRoute
  TechnologyRoute: typeof TechnologyRoute
  WasteToEnergyRoute: typeof WasteToEnergyRoute
  WindRoute: typeof WindRoute
  ZonesRoute: typeof ZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biomass': {
      id: '/biomass'
      path: '/biomass'
      fullPath: '/biomass'
      preLoaderRoute: typeof BiomassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadshield': {
      id: '/loadshield'
      path: '/loadshield'
      fullPath: '/loadshield'
      preLoaderRoute: typeof LoadshieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waste-to-energy': {
      id: '/waste-to-energy'
      path: '/waste-to-energy'
      fullPath: '/waste-to-energy'
      preLoaderRoute: typeof WasteToEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wind': {
      id: '/wind'
      path: '/wind'
      fullPath: '/wind'
      preLoaderRoute: typeof WindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BiomassRoute: BiomassRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoadshieldRoute: LoadshieldRoute,
  ResourcesRoute: ResourcesRoute,
  SolarRoute: SolarRoute,
  TechnologyRoute: TechnologyRoute,
  WasteToEnergyRoute: WasteToEnergyRoute,
  WindRoute: WindRoute,
  ZonesRoute: ZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
